application: rollercredi
version: 0-1
runtime: python
api_version: 1

handlers:
- url: /vote.*
  script: vote.py

- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: index.py
